language: php

php:
 - '5.6.12'

install:
 - travis_retry composer install --no-interaction --prefer-dist --no-suggest
 - cp .env.travis .env # Create a new .env file
 - php artisan key:generate # Generate application key
 - php artisan migrate #create the tables on database

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS laravelangular;'

before_script:
 - phantomjs --webdriver=127.0.0.1:9515 & # Start PhantomJS driver
 - php artisan serve --port=8081 & # Start server
 - sleep 5 # Give PhantomJS and Artisan time to start


services: mysql

script: php artisan dusk

deploy:
  provider: heroku
  api_key:
    secure: "e7987104-ca88-4b83-8123-ba19c0d7b056"